import { useEffect, useState } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';

const API = 'https://pharmacy-order-backend.onrender.com/api';

const CATEGORY_LABELS = {
  GENERIC: '💊 Generic',
  ETHICAL: '💉 Ethical',
  GENERAL: '🛒 General Items'
};

const CATEGORY_COLORS = {
  GENERIC: '#1a73e8',
  ETHICAL: '#7b1fa2',
  GENERAL: '#2e7d32'
};

const downloadPDF = (order) => {
  const doc = new jsPDF();
  const color = order.category === 'GENERIC' ? [26,115,232] : order.category === 'ETHICAL' ? [123,31,162] : [46,125,50];

  doc.setFillColor(...color);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${CATEGORY_LABELS[order.category] || ''} Order`, 14, 20);

  doc.setTextColor(50, 50, 50);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Order #${order.id}`, 14, 42);
  doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`, 14, 50);
  doc.text(`Status: Confirmed`, 14, 58);

  doc.setDrawColor(200, 200, 200);
  doc.line(14, 63, 196, 63);

  doc.setFillColor(240, 244, 248);
  doc.rect(14, 66, 182, 9, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text('Medicine Name', 18, 73);
  doc.text('Unit', 130, 73);
  doc.text('Qty', 175, 73);

  doc.setFont('helvetica', 'normal');
  let y = 83;
  order.items.forEach((item, index) => {
    if (index % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(14, y - 6, 182, 9, 'F');
    }
    doc.setTextColor(50, 50, 50);
    doc.text(item.medicine.name, 18, y);
    doc.text(item.medicine.unit || '-', 130, y);
    doc.text(String(item.quantity), 175, y);
    y += 10;
  });

  doc.setDrawColor(200, 200, 200);
  doc.line(14, y + 4, 196, y + 4);
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Pharmacy Order Manager', 14, y + 12);

  doc.save(`order-${order.category}-${order.id}.pdf`);
};

export default function OrderHistory() {
  const [orders, setOrders] = useState([]);
  const [confirmDelete, setConfirmDelete] = useState(null);
  const [filterCat, setFilterCat] = useState('ALL');

  useEffect(() => { fetchOrders(); }, []);

  const fetchOrders = () => {
    axios.get(`${API}/orders`).then(r => setOrders(r.data));
  };

  const deleteOrder = async (id) => {
    await axios.delete(`${API}/orders/${id}`);
    setConfirmDelete(null);
    fetchOrders();
  };

  const confirmed = orders.filter(o =>
    o.status === 'CONFIRMED' &&
    (filterCat === 'ALL' || o.category === filterCat)
  );

  return (
    <div className="container">
      <p className="page-title">Order History</p>

      {/* Filter Tabs */}
      <div style={{display:'flex',gap:'8px',marginBottom:'1.5rem',flexWrap:'wrap'}}>
        {['ALL','GENERIC','ETHICAL','GENERAL'].map(cat => (
          <button
            key={cat}
            onClick={() => setFilterCat(cat)}
            style={{
              padding:'7px 18px',
              borderRadius:'20px',
              border: filterCat === cat ? 'none' : '1.5px solid #ddd',
              background: filterCat === cat ? '#1a73e8' : 'white',
              color: filterCat === cat ? 'white' : '#555',
              fontWeight: filterCat === cat ? 600 : 400,
              cursor:'pointer',
              fontSize:'0.85rem'
            }}
          >
            {cat === 'ALL' ? '📋 All' : CATEGORY_LABELS[cat]}
          </button>
        ))}
      </div>

      {/* Delete Confirmation Popup */}
      {confirmDelete && (
        <div style={{position:'fixed',top:0,left:0,width:'100%',height:'100%',background:'rgba(0,0,0,0.4)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000}}>
          <div style={{background:'white',borderRadius:'12px',padding:'2rem',width:'320px',textAlign:'center',boxShadow:'0 4px 20px rgba(0,0,0,0.2)'}}>
            <div style={{fontSize:'2.5rem',marginBottom:'1rem'}}>🗑️</div>
            <h3 style={{marginBottom:'0.5rem'}}>Delete Order #{confirmDelete}?</h3>
            <p style={{color:'#666',fontSize:'0.9rem',marginBottom:'1.5rem'}}>This action cannot be undone.</p>
            <div style={{display:'flex',gap:'10px',justifyContent:'center'}}>
              <button className="btn btn-danger" onClick={() => deleteOrder(confirmDelete)}>Yes, Delete</button>
              <button className="btn btn-outline" onClick={() => setConfirmDelete(null)}>Cancel</button>
            </div>
          </div>
        </div>
      )}

      {confirmed.length === 0 && (
        <div className="empty-state">No confirmed orders found.</div>
      )}

      {confirmed.map(order => {
        const color = CATEGORY_COLORS[order.category] || '#1a73e8';
        return (
          <div key={order.id} style={{background:'white',borderRadius:'10px',boxShadow:'0 1px 4px rgba(0,0,0,0.1)',marginBottom:'1rem',overflow:'hidden'}}>

            {/* Header */}
            <div style={{background:color,padding:'10px 16px',display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:'8px'}}>
              <span style={{color:'white',fontWeight:600}}>{CATEGORY_LABELS[order.category] || order.category} — Order #{order.id}</span>
              <span style={{color:'white',fontSize:'0.85rem'}}>{new Date(order.createdAt).toLocaleDateString()}</span>
            </div>

            {/* Body */}
            <div style={{padding:'1rem'}}>
              {/* Table Header */}
              <div style={{display:'grid',gridTemplateColumns:'2fr 1fr 0.5fr',padding:'6px 8px',background:'#f0f4f8',borderRadius:'6px',marginBottom:'6px',fontSize:'0.82rem',fontWeight:600,color:'#555'}}>
                <span>Medicine</span>
                <span>Unit</span>
                <span>Qty</span>
              </div>

              {order.items && order.items.map((item, index) => (
                <div key={item.id} style={{display:'grid',gridTemplateColumns:'2fr 1fr 0.5fr',padding:'7px 8px',background: index % 2 === 0 ? '#fafafa' : 'white',borderRadius:'4px',fontSize:'0.9rem'}}>
                  <span style={{fontWeight:500}}>{item.medicine.name}</span>
                  <span style={{color:'#666'}}>{item.medicine.unit}</span>
                  <span style={{fontWeight:600,color:color}}>{item.quantity}</span>
                </div>
              ))}

              {/* Footer */}
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:'12px'}}>
                <span style={{fontSize:'0.85rem',color:'#888'}}>{order.items ? order.items.length : 0} item(s)</span>
                <div style={{display:'flex',gap:'8px'}}>
                  <button className="btn btn-primary" style={{fontSize:'0.85rem',padding:'6px 14px'}} onClick={() => downloadPDF(order)}>⬇ PDF</button>
                  <button className="btn btn-danger" style={{fontSize:'0.85rem',padding:'6px 14px'}} onClick={() => setConfirmDelete(order.id)}>🗑️ Delete</button>
                </div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
